name: Cypress Test Pipeline

on:
  push:
    branches:
      - main
jobs:
  cypress-run:

    runs-on: ubuntu-latest

    steps:

      # Paso 1: Hacer checkout del código
      - name: Checkout repository
        uses: actions/checkout@v2

      # Paso 2: Ejecutar las pruebas de Cypress
      - name: Run Cypress tests
        run: npx cypress run --headless --browser chrome
