name: Cypress E2E Tests

# Cuándo ejecutar el pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # 3. Instalar dependencias
      - name: Install dependencies
        run: npm install

      # 4. Iniciar la aplicación (si es necesario)
      - name: Start application
        run: npm start &
        env:
          CI: true

      # 5. Esperar que la aplicación esté lista
      - name: Wait for application to be ready
        run: npx wait-on http://localhost:3000

      # 6. Ejecutar las pruebas de Cypress
      - name: Run Cypress tests
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
