name: Cypress Test Pipeline

on:
  push:
    branches:
      - main
jobs:
  cypress-run:

    runs-on: ubuntu-latest

    steps:

      # Paso 4: Ejecutar las pruebas de Cypress
      - name: Run Cypress tests
        run: npx cypress run --headless --browser chrome
